name: Deploy to Heroku

on:
  push:
    branches:
      - main  # or the branch you want to deploy from


      blah blah test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'  # Specify your Ruby version here

      - name: Install Ruby gems
        run: bundle install

      - name: Run RSpec tests
        run: bundle exec rspec

      - name: Deploy to Heroku
        if: success()
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/utah-aba-finder-api.git
          git push heroku main
