name: deploy

on:
  push:
    branches:
      - main  # or the branch you want to deploy from
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: utah_aba_finder_api_test
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://user:password@localhost:5432/utah_aba_finder_api_test"
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      HOST: "localhost:3000"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'

      - name: Install Ruby gems
        run: bundle install
        
      - name: Set up Rails credentials
        run: |
          echo "Setting up Rails credentials..."
          bin/rails credentials:edit --environment test || echo "Credentials setup skipped"

      - name: Wait for PostgreSQL
        run: sleep 10
        
      - name: Set up database
        run: |
          bin/rails db:drop || true
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:seed || true
          bin/rails runner db/seeds_provider_categories.rb
          
      - name: Verify database setup
        run: |
          bin/rails runner "puts 'Database tables:'; puts ActiveRecord::Base.connection.tables.sort.join(', ')"
          bin/rails runner "puts 'ProviderCategory count:'; puts ProviderCategory.count"

      - name: Run RSpec tests
        run: bundle exec rspec